num1 = input("Please give me a number with no commas and no words:")
num2 = input("Please give me another number with no commas and no words:")
num1 = int(num1)
num2 = int(num2)
print("When your numbers are added you get")
print(num1+num2)
print("When your numbers are subtracted you get")
print(num1-num2)
print("When your numbers are multiplied you get")
print(num1*num2)
print("When your numbers are divided you get")
print(num1/num2)
